services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: next-app
    container_name: next-app
    ports:
      - '3001:3001'
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./app:/app/app
      - ./lib:/app/lib
      - node_modules:/app/node_modules
    restart: always
    tty: true
    stdin_open: true

volumes:
  node_modules:
