name: "Setup and Install"
description: "Setup and install dependencies"

runs:
  using: "composite"
  steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-node@v4"
      with:
        node-version: "20"
        cache: "pnpm"
    - shell: bash
      run: pnpm install