name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup
        uses: ./.github/setup

      - name: Lint
        run: pnpm lint
        