name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # .envの作成
      - name: Create dot env file
        shell: bash
        run: |
          touch .env
          echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" >> .env

      - name: Install Dependencies
        run: pnpm install

      # Testing
      # - name: Test
        # run: pnpm test
        